<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.2 setup script
 * Date: Tue, 05 Jul 2011 20:44:35 +1200
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>